export const SEARCH_TERM = 'SEARCH_TERM';
export const PROBLEM_SETS = 'PROBLEM_SETS';
export const SET_USER = 'SET_USER';
export const SET_USER_FAILURE = 'SET_USER_FAILURE';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
